/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Character = IDL.Record({
  'name' : IDL.Text,
  'description' : IDL.Text,
  'speed' : IDL.Nat,
  'strength' : IDL.Nat,
  'agility' : IDL.Nat,
});
export const GameMap = IDL.Record({ 'theme' : IDL.Text, 'name' : IDL.Text });
export const GunSkin = IDL.Record({
  'name' : IDL.Text,
  'description' : IDL.Text,
  'rarity' : IDL.Nat,
});
export const VehicleType = IDL.Variant({
  'car' : IDL.Null,
  'van' : IDL.Null,
  'bike' : IDL.Null,
  'ship' : IDL.Null,
  'tank' : IDL.Null,
  'battle' : IDL.Null,
  'plane' : IDL.Null,
});
export const Vehicle = IDL.Record({
  'vehicleType' : VehicleType,
  'armor' : IDL.Nat,
  'firepower' : IDL.Nat,
  'name' : IDL.Text,
  'speed' : IDL.Nat,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const MatchResult = IDL.Record({
  'vehicleUsed' : IDL.Text,
  'mapUsed' : IDL.Text,
  'characterUsed' : IDL.Text,
  'winner' : IDL.Principal,
  'loser' : IDL.Principal,
  'timestamp' : Time,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'favoriteVehicle' : IDL.Text,
  'favoriteCharacter' : IDL.Text,
});
export const GodModeFlags = IDL.Record({
  'flyMode' : IDL.Bool,
  'extraCoins' : IDL.Nat,
  'invincibility' : IDL.Bool,
});
export const PlayerSession = IDL.Record({
  'status' : IDL.Variant({ 'alive' : IDL.Null, 'dead' : IDL.Null }),
  'vehicleName' : IDL.Text,
  'principal' : IDL.Principal,
  'displayName' : IDL.Text,
  'characterName' : IDL.Text,
  'coins' : IDL.Nat,
  'score' : IDL.Nat,
  'isReady' : IDL.Bool,
  'positionX' : IDL.Int,
  'positionY' : IDL.Int,
  'gunSkinName' : IDL.Text,
  'health' : IDL.Nat,
});
export const RoomStatus = IDL.Variant({
  'playing' : IDL.Null,
  'finished' : IDL.Null,
  'waiting' : IDL.Null,
});
export const RoomPlayer = IDL.Record({
  'vehicleName' : IDL.Text,
  'principal' : IDL.Principal,
  'displayName' : IDL.Text,
  'characterName' : IDL.Text,
  'isReady' : IDL.Bool,
  'gunSkinName' : IDL.Text,
});
export const Room = IDL.Record({
  'id' : IDL.Nat,
  'status' : RoomStatus,
  'selectedMap' : IDL.Text,
  'code' : IDL.Text,
  'createdAt' : Time,
  'players' : IDL.Vec(RoomPlayer),
  'hostPrincipal' : IDL.Principal,
});
export const ChatMessage = IDL.Record({
  'displayName' : IDL.Text,
  'senderPrincipal' : IDL.Principal,
  'message' : IDL.Text,
  'timestamp' : Time,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addCharacter' : IDL.Func([Character], [IDL.Nat], []),
  'addGameMap' : IDL.Func([GameMap], [IDL.Nat], []),
  'addGunSkin' : IDL.Func([GunSkin], [IDL.Nat], []),
  'addVehicle' : IDL.Func([Vehicle], [IDL.Nat], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'banPlayer' : IDL.Func([IDL.Principal], [], []),
  'checkIfBanned' : IDL.Func([IDL.Principal], [IDL.Bool], ['query']),
  'createRoom' : IDL.Func([IDL.Text], [IDL.Text], []),
  'deleteCharacter' : IDL.Func([IDL.Nat], [], []),
  'deleteGameMap' : IDL.Func([IDL.Nat], [], []),
  'deleteGunSkin' : IDL.Func([IDL.Nat], [], []),
  'deleteVehicle' : IDL.Func([IDL.Nat], [], []),
  'endMatch' : IDL.Func([IDL.Text], [], []),
  'getAllCharacters' : IDL.Func([], [IDL.Vec(Character)], ['query']),
  'getAllGunSkins' : IDL.Func([], [IDL.Vec(GunSkin)], ['query']),
  'getAllMaps' : IDL.Func([], [IDL.Vec(GameMap)], ['query']),
  'getAllMatchResults' : IDL.Func([], [IDL.Vec(MatchResult)], ['query']),
  'getAllVehicles' : IDL.Func([], [IDL.Vec(Vehicle)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getGodMode' : IDL.Func([IDL.Principal], [IDL.Opt(GodModeFlags)], ['query']),
  'getPlayerSession' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(PlayerSession)],
      ['query'],
    ),
  'getRoomByCode' : IDL.Func([IDL.Text], [IDL.Opt(Room)], ['query']),
  'getRoomMessages' : IDL.Func([IDL.Text], [IDL.Vec(ChatMessage)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'joinRandomRoom' : IDL.Func([IDL.Text], [IDL.Text], []),
  'joinRoom' : IDL.Func([IDL.Text, IDL.Text], [Room], []),
  'leaveRoom' : IDL.Func([IDL.Text], [], []),
  'listBannedPlayers' : IDL.Func([], [IDL.Vec(IDL.Principal)], ['query']),
  'listOpenRooms' : IDL.Func([], [IDL.Vec(Room)], ['query']),
  'removeGodMode' : IDL.Func([IDL.Principal], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'seedInitialData' : IDL.Func([], [], []),
  'sendChatMessage' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'setGodMode' : IDL.Func([IDL.Principal, GodModeFlags], [], []),
  'setPlayerReady' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Text], [], []),
  'setRoomMap' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'startMatch' : IDL.Func([IDL.Text], [], []),
  'submitMatchResult' : IDL.Func(
      [IDL.Principal, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'unbanPlayer' : IDL.Func([IDL.Principal], [], []),
  'updateCharacter' : IDL.Func([IDL.Nat, Character], [], []),
  'updateGameMap' : IDL.Func([IDL.Nat, GameMap], [], []),
  'updateGunSkin' : IDL.Func([IDL.Nat, GunSkin], [], []),
  'updatePlayerSession' : IDL.Func([PlayerSession], [], []),
  'updateVehicle' : IDL.Func([IDL.Nat, Vehicle], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Character = IDL.Record({
    'name' : IDL.Text,
    'description' : IDL.Text,
    'speed' : IDL.Nat,
    'strength' : IDL.Nat,
    'agility' : IDL.Nat,
  });
  const GameMap = IDL.Record({ 'theme' : IDL.Text, 'name' : IDL.Text });
  const GunSkin = IDL.Record({
    'name' : IDL.Text,
    'description' : IDL.Text,
    'rarity' : IDL.Nat,
  });
  const VehicleType = IDL.Variant({
    'car' : IDL.Null,
    'van' : IDL.Null,
    'bike' : IDL.Null,
    'ship' : IDL.Null,
    'tank' : IDL.Null,
    'battle' : IDL.Null,
    'plane' : IDL.Null,
  });
  const Vehicle = IDL.Record({
    'vehicleType' : VehicleType,
    'armor' : IDL.Nat,
    'firepower' : IDL.Nat,
    'name' : IDL.Text,
    'speed' : IDL.Nat,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const MatchResult = IDL.Record({
    'vehicleUsed' : IDL.Text,
    'mapUsed' : IDL.Text,
    'characterUsed' : IDL.Text,
    'winner' : IDL.Principal,
    'loser' : IDL.Principal,
    'timestamp' : Time,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'favoriteVehicle' : IDL.Text,
    'favoriteCharacter' : IDL.Text,
  });
  const GodModeFlags = IDL.Record({
    'flyMode' : IDL.Bool,
    'extraCoins' : IDL.Nat,
    'invincibility' : IDL.Bool,
  });
  const PlayerSession = IDL.Record({
    'status' : IDL.Variant({ 'alive' : IDL.Null, 'dead' : IDL.Null }),
    'vehicleName' : IDL.Text,
    'principal' : IDL.Principal,
    'displayName' : IDL.Text,
    'characterName' : IDL.Text,
    'coins' : IDL.Nat,
    'score' : IDL.Nat,
    'isReady' : IDL.Bool,
    'positionX' : IDL.Int,
    'positionY' : IDL.Int,
    'gunSkinName' : IDL.Text,
    'health' : IDL.Nat,
  });
  const RoomStatus = IDL.Variant({
    'playing' : IDL.Null,
    'finished' : IDL.Null,
    'waiting' : IDL.Null,
  });
  const RoomPlayer = IDL.Record({
    'vehicleName' : IDL.Text,
    'principal' : IDL.Principal,
    'displayName' : IDL.Text,
    'characterName' : IDL.Text,
    'isReady' : IDL.Bool,
    'gunSkinName' : IDL.Text,
  });
  const Room = IDL.Record({
    'id' : IDL.Nat,
    'status' : RoomStatus,
    'selectedMap' : IDL.Text,
    'code' : IDL.Text,
    'createdAt' : Time,
    'players' : IDL.Vec(RoomPlayer),
    'hostPrincipal' : IDL.Principal,
  });
  const ChatMessage = IDL.Record({
    'displayName' : IDL.Text,
    'senderPrincipal' : IDL.Principal,
    'message' : IDL.Text,
    'timestamp' : Time,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addCharacter' : IDL.Func([Character], [IDL.Nat], []),
    'addGameMap' : IDL.Func([GameMap], [IDL.Nat], []),
    'addGunSkin' : IDL.Func([GunSkin], [IDL.Nat], []),
    'addVehicle' : IDL.Func([Vehicle], [IDL.Nat], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'banPlayer' : IDL.Func([IDL.Principal], [], []),
    'checkIfBanned' : IDL.Func([IDL.Principal], [IDL.Bool], ['query']),
    'createRoom' : IDL.Func([IDL.Text], [IDL.Text], []),
    'deleteCharacter' : IDL.Func([IDL.Nat], [], []),
    'deleteGameMap' : IDL.Func([IDL.Nat], [], []),
    'deleteGunSkin' : IDL.Func([IDL.Nat], [], []),
    'deleteVehicle' : IDL.Func([IDL.Nat], [], []),
    'endMatch' : IDL.Func([IDL.Text], [], []),
    'getAllCharacters' : IDL.Func([], [IDL.Vec(Character)], ['query']),
    'getAllGunSkins' : IDL.Func([], [IDL.Vec(GunSkin)], ['query']),
    'getAllMaps' : IDL.Func([], [IDL.Vec(GameMap)], ['query']),
    'getAllMatchResults' : IDL.Func([], [IDL.Vec(MatchResult)], ['query']),
    'getAllVehicles' : IDL.Func([], [IDL.Vec(Vehicle)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getGodMode' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(GodModeFlags)],
        ['query'],
      ),
    'getPlayerSession' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(PlayerSession)],
        ['query'],
      ),
    'getRoomByCode' : IDL.Func([IDL.Text], [IDL.Opt(Room)], ['query']),
    'getRoomMessages' : IDL.Func([IDL.Text], [IDL.Vec(ChatMessage)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'joinRandomRoom' : IDL.Func([IDL.Text], [IDL.Text], []),
    'joinRoom' : IDL.Func([IDL.Text, IDL.Text], [Room], []),
    'leaveRoom' : IDL.Func([IDL.Text], [], []),
    'listBannedPlayers' : IDL.Func([], [IDL.Vec(IDL.Principal)], ['query']),
    'listOpenRooms' : IDL.Func([], [IDL.Vec(Room)], ['query']),
    'removeGodMode' : IDL.Func([IDL.Principal], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'seedInitialData' : IDL.Func([], [], []),
    'sendChatMessage' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'setGodMode' : IDL.Func([IDL.Principal, GodModeFlags], [], []),
    'setPlayerReady' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'setRoomMap' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'startMatch' : IDL.Func([IDL.Text], [], []),
    'submitMatchResult' : IDL.Func(
        [IDL.Principal, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'unbanPlayer' : IDL.Func([IDL.Principal], [], []),
    'updateCharacter' : IDL.Func([IDL.Nat, Character], [], []),
    'updateGameMap' : IDL.Func([IDL.Nat, GameMap], [], []),
    'updateGunSkin' : IDL.Func([IDL.Nat, GunSkin], [], []),
    'updatePlayerSession' : IDL.Func([PlayerSession], [], []),
    'updateVehicle' : IDL.Func([IDL.Nat, Vehicle], [], []),
  });
};

export const init = ({ IDL }) => { return []; };