/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Character = IDL.Record({
  'name' : IDL.Text,
  'description' : IDL.Text,
  'speed' : IDL.Nat,
  'strength' : IDL.Nat,
  'agility' : IDL.Nat,
});
export const GameMap = IDL.Record({ 'theme' : IDL.Text, 'name' : IDL.Text });
export const GunSkin = IDL.Record({
  'name' : IDL.Text,
  'description' : IDL.Text,
  'rarity' : IDL.Nat,
});
export const VehicleType = IDL.Variant({
  'car' : IDL.Null,
  'van' : IDL.Null,
  'bike' : IDL.Null,
  'ship' : IDL.Null,
  'tank' : IDL.Null,
  'battle' : IDL.Null,
  'plane' : IDL.Null,
});
export const Vehicle = IDL.Record({
  'vehicleType' : VehicleType,
  'armor' : IDL.Nat,
  'firepower' : IDL.Nat,
  'name' : IDL.Text,
  'speed' : IDL.Nat,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const MatchResult = IDL.Record({
  'vehicleUsed' : IDL.Text,
  'mapUsed' : IDL.Text,
  'characterUsed' : IDL.Text,
  'winner' : IDL.Principal,
  'loser' : IDL.Principal,
  'timestamp' : Time,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'favoriteVehicle' : IDL.Text,
  'favoriteCharacter' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addCharacter' : IDL.Func([Character], [IDL.Nat], []),
  'addGameMap' : IDL.Func([GameMap], [IDL.Nat], []),
  'addGunSkin' : IDL.Func([GunSkin], [IDL.Nat], []),
  'addVehicle' : IDL.Func([Vehicle], [IDL.Nat], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteCharacter' : IDL.Func([IDL.Nat], [], []),
  'deleteGameMap' : IDL.Func([IDL.Nat], [], []),
  'deleteGunSkin' : IDL.Func([IDL.Nat], [], []),
  'deleteVehicle' : IDL.Func([IDL.Nat], [], []),
  'getAllCharacters' : IDL.Func([], [IDL.Vec(Character)], ['query']),
  'getAllGunSkins' : IDL.Func([], [IDL.Vec(GunSkin)], ['query']),
  'getAllMaps' : IDL.Func([], [IDL.Vec(GameMap)], ['query']),
  'getAllMatchResults' : IDL.Func([], [IDL.Vec(MatchResult)], ['query']),
  'getAllVehicles' : IDL.Func([], [IDL.Vec(Vehicle)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'seedInitialData' : IDL.Func([], [], []),
  'submitMatchResult' : IDL.Func(
      [IDL.Principal, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'updateCharacter' : IDL.Func([IDL.Nat, Character], [], []),
  'updateGameMap' : IDL.Func([IDL.Nat, GameMap], [], []),
  'updateGunSkin' : IDL.Func([IDL.Nat, GunSkin], [], []),
  'updateVehicle' : IDL.Func([IDL.Nat, Vehicle], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Character = IDL.Record({
    'name' : IDL.Text,
    'description' : IDL.Text,
    'speed' : IDL.Nat,
    'strength' : IDL.Nat,
    'agility' : IDL.Nat,
  });
  const GameMap = IDL.Record({ 'theme' : IDL.Text, 'name' : IDL.Text });
  const GunSkin = IDL.Record({
    'name' : IDL.Text,
    'description' : IDL.Text,
    'rarity' : IDL.Nat,
  });
  const VehicleType = IDL.Variant({
    'car' : IDL.Null,
    'van' : IDL.Null,
    'bike' : IDL.Null,
    'ship' : IDL.Null,
    'tank' : IDL.Null,
    'battle' : IDL.Null,
    'plane' : IDL.Null,
  });
  const Vehicle = IDL.Record({
    'vehicleType' : VehicleType,
    'armor' : IDL.Nat,
    'firepower' : IDL.Nat,
    'name' : IDL.Text,
    'speed' : IDL.Nat,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const MatchResult = IDL.Record({
    'vehicleUsed' : IDL.Text,
    'mapUsed' : IDL.Text,
    'characterUsed' : IDL.Text,
    'winner' : IDL.Principal,
    'loser' : IDL.Principal,
    'timestamp' : Time,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'favoriteVehicle' : IDL.Text,
    'favoriteCharacter' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addCharacter' : IDL.Func([Character], [IDL.Nat], []),
    'addGameMap' : IDL.Func([GameMap], [IDL.Nat], []),
    'addGunSkin' : IDL.Func([GunSkin], [IDL.Nat], []),
    'addVehicle' : IDL.Func([Vehicle], [IDL.Nat], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteCharacter' : IDL.Func([IDL.Nat], [], []),
    'deleteGameMap' : IDL.Func([IDL.Nat], [], []),
    'deleteGunSkin' : IDL.Func([IDL.Nat], [], []),
    'deleteVehicle' : IDL.Func([IDL.Nat], [], []),
    'getAllCharacters' : IDL.Func([], [IDL.Vec(Character)], ['query']),
    'getAllGunSkins' : IDL.Func([], [IDL.Vec(GunSkin)], ['query']),
    'getAllMaps' : IDL.Func([], [IDL.Vec(GameMap)], ['query']),
    'getAllMatchResults' : IDL.Func([], [IDL.Vec(MatchResult)], ['query']),
    'getAllVehicles' : IDL.Func([], [IDL.Vec(Vehicle)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'seedInitialData' : IDL.Func([], [], []),
    'submitMatchResult' : IDL.Func(
        [IDL.Principal, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'updateCharacter' : IDL.Func([IDL.Nat, Character], [], []),
    'updateGameMap' : IDL.Func([IDL.Nat, GameMap], [], []),
    'updateGunSkin' : IDL.Func([IDL.Nat, GunSkin], [], []),
    'updateVehicle' : IDL.Func([IDL.Nat, Vehicle], [], []),
  });
};

export const init = ({ IDL }) => { return []; };