/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Character {
  'name' : string,
  'description' : string,
  'speed' : bigint,
  'strength' : bigint,
  'agility' : bigint,
}
export interface GameMap { 'theme' : string, 'name' : string }
export interface GunSkin {
  'name' : string,
  'description' : string,
  'rarity' : bigint,
}
export interface MatchResult {
  'vehicleUsed' : string,
  'mapUsed' : string,
  'characterUsed' : string,
  'winner' : Principal,
  'loser' : Principal,
  'timestamp' : Time,
}
export type Time = bigint;
export interface UserProfile {
  'name' : string,
  'favoriteVehicle' : string,
  'favoriteCharacter' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface Vehicle {
  'vehicleType' : VehicleType,
  'armor' : bigint,
  'firepower' : bigint,
  'name' : string,
  'speed' : bigint,
}
export type VehicleType = { 'car' : null } |
  { 'van' : null } |
  { 'bike' : null } |
  { 'ship' : null } |
  { 'tank' : null } |
  { 'battle' : null } |
  { 'plane' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addCharacter' : ActorMethod<[Character], bigint>,
  'addGameMap' : ActorMethod<[GameMap], bigint>,
  'addGunSkin' : ActorMethod<[GunSkin], bigint>,
  'addVehicle' : ActorMethod<[Vehicle], bigint>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteCharacter' : ActorMethod<[bigint], undefined>,
  'deleteGameMap' : ActorMethod<[bigint], undefined>,
  'deleteGunSkin' : ActorMethod<[bigint], undefined>,
  'deleteVehicle' : ActorMethod<[bigint], undefined>,
  'getAllCharacters' : ActorMethod<[], Array<Character>>,
  'getAllGunSkins' : ActorMethod<[], Array<GunSkin>>,
  'getAllMaps' : ActorMethod<[], Array<GameMap>>,
  'getAllMatchResults' : ActorMethod<[], Array<MatchResult>>,
  'getAllVehicles' : ActorMethod<[], Array<Vehicle>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'seedInitialData' : ActorMethod<[], undefined>,
  'submitMatchResult' : ActorMethod<
    [Principal, string, string, string],
    bigint
  >,
  'updateCharacter' : ActorMethod<[bigint, Character], undefined>,
  'updateGameMap' : ActorMethod<[bigint, GameMap], undefined>,
  'updateGunSkin' : ActorMethod<[bigint, GunSkin], undefined>,
  'updateVehicle' : ActorMethod<[bigint, Vehicle], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];